/**
 * 国际化语言包 - 英文
 */
export default {
  // Common
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    ok: 'OK',
  },

  // PromptEditor Component
  editor: {
    addRootNode: 'Add Root Title',
    nodeLocked: 'Node locked',
    nodeUnlocked: 'Node unlocked',
    nodeDeleted: 'Node deleted',
    childNodeAdded: 'Child node added successfully',
    rootTitleAdded: 'Root title added successfully',
    dependencyAdded: 'Dependency added successfully',
    dependencyRemoved: 'Dependency removed',
    expandEditor: 'Expand Editor',
    collapseEditor: 'Collapse Editor',
    addChildNode: 'Add Child Node',
    lockNode: 'Lock Node',
    unlockNode: 'Unlock Node',
    deleteNode: 'Delete Node',
    lockedCannotAddChild: 'Node is locked, cannot add child nodes',
    lockedCannotDelete: 'Node is locked, cannot delete',
    lockedCannotEdit: 'Node is locked, cannot edit',
    previewModeNoEdit: 'Cannot edit in preview mode',
    notRun: 'Not Run',
    runFirst: 'Please run first',
    childTitle: 'Child Title',
    lock: 'Lock',
    unlock: 'Unlock',
    deleteConfirmTitle: 'Delete Node',
    deleteConfirmDesc: 'Are you sure you want to delete this node?',
    cancelledDelete: 'Delete cancelled',
    editPrompt: 'Edit Prompt',
    run: 'Run',
    aiOptimize: 'AI Optimize',
    expandChildren: 'Expand Children',
    collapseChildren: 'Collapse Children',
    titleUpdated: 'Title modified successfully',
    missingOnRunRequest: 'Please provide onRunRequest callback',
  },

  // Node Action Buttons
  node: {
    run: 'Run',
    aiOptimize: 'AI Optimize',
    expandChildren: 'Expand Children',
    collapseChildren: 'Collapse Children',
  },

  // Dependency Configuration
  dependency: {
    dependencies: 'Dependencies',
    selectDependencyPlaceholder:
      'Select dependency nodes (only locked nodes can be selected)',
    canOnlySelectLockedNodes:
      'Only locked nodes with earlier sequence numbers can be selected',
    noDependencies:
      'No dependencies yet. Click below to add (only locked predecessor nodes)',
    locked: 'Locked',
  },

  // AI Optimization Modal
  optimize: {
    title: 'AI Prompt Optimization',
    userRole: 'User',
    aiRole: 'AI',
    selectedContent: '{length} characters selected',
    selectedContentHint: 'Selected content ({length} characters)',
    inputPlaceholder: 'Enter optimization instructions...',
    inputPlaceholderWithSelection:
      'Enter optimization instructions ({length} characters selected)',
    apply: 'Replace',
    exit: 'Exit',
    disclaimer:
      'Content generated by AI, accuracy not guaranteed, for reference only.',
    copied: 'Copied to clipboard',
    optimizeFailed: 'Optimization failed, please retry',
    noOptimizeContent: 'No optimized content to apply',
    contentApplied: 'Optimized content applied',
    replaceSelected: 'Selected content replaced',
    replaceAll: 'All content replaced',
    replaceFailed: 'Replacement failed, please retry',
    optimizeComplete: 'Optimization complete',
    emptyState:
      'Enter optimization instructions, AI will optimize the prompt for you',
    provideCallback: 'Please provide onOptimizeRequest callback',
    provideConfigOrCallback: 'Please configure optimizeConfig or provide onOptimizeRequest callback',
    autoOptimize: 'Please optimize this prompt to make it more professional, clear, and efficient.',
    autoOptimizeWithSelection: 'Please optimize this prompt based on the selected {length} characters to make it more professional, clear, and efficient.',
  },

  // AI Optimization Messages
  aiOptimize: {
    replacedSelectedContent: 'Selected content replaced',
    replacedAllContent: 'All content replaced',
    replaceFailed: 'Replacement failed, please retry',
  },

  // CodeMirror Editor
  editor_toolbar: {
    undo: 'Undo (Ctrl+Z)',
    redo: 'Redo (Ctrl+Y)',
  },

  // CodeMirror UI Text
  codemirror: {
    search: 'Search',
    replace: 'Replace',
    replaceAll: 'Replace All',
    caseSensitive: 'Case Sensitive',
    wholeWord: 'Whole Word',
    regexp: 'Regular Expression',
    previousMatch: 'Previous Match',
    nextMatch: 'Next Match',
    close: 'Close',
    findPlaceholder: 'Find...',
    replacePlaceholder: 'Replace with...',
  },

  // Messages
  message: {
    titleModified: 'Title modified successfully',
    titleEmpty: 'Title cannot be empty',
    editCancelled: 'Edit cancelled',
    clickToLoad: 'Click to load editor...',
  },
};
